# Generated by Django 5.2 on 2025-09-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_addressmodel_selectedaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='selectedaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
        migrations.DeleteModel(
            name='SelectedAddress',
        ),
    ]
