# Generated by Django 5.2 on 2025-09-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_addressmodel_selectedaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='Plaque',
            new_name='plaque',
        ),
        migrations.RenameField(
            model_name='addressmodel',
            old_name='Postcode',
            new_name='postcode',
        ),
    ]
