# Generated by Django 5.2 on 2025-09-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_plaque_addressmodel_plaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='isSelected',
            field=models.BooleanField(default=False),
        ),
    ]
