# Generated by Django 5.2 on 2025-09-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_addressmodel_isselected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedAddress',
        ),
    ]
