version: '3.9'

services:

  web:
    build:
      context: .
      network: host
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=restframework
      - DB_USER=saber
      - DB_PASSWORD=saber
      - DB_HOST=db
      - DB_PORT=5432


  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: restframework
      POSTGRES_USER: saber
      POSTGRES_PASSWORD: saber
volumes:
  postgres_data:
