# Generated by Django 5.2 on 2025-09-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='post_kind',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver_phone',
        ),
    ]
