# Generated by Django 5.2 on 2025-09-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_ordermodel_post_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.JSONField(null=True),
        ),
    ]
