# Generated by Django 5.2 on 2025-09-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_rom_name'),
        ('order', '0003_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitemmodel',
            unique_together={('order', 'product', 'color')},
        ),
    ]
