# Generated by Django 5.2 on 2025-08-03 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='par',
            new_name='parent',
        ),
    ]
