# Generated by Django 5.2 on 2025-09-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=20)),
                ('color_code', models.CharField(max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField(default=1)),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.cpu')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.memory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.product')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.rom')),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
