# Generated by Django 5.2 on 2025-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_cpu_memory_rom_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='image/productImage'),
        ),
    ]
