# Generated by Django 5.2 on 2025-09-03 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_productimages_image1_productimages_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image9',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='property',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ram',
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.cpu'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.memory'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.rom'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='rom',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
