# Generated by Django 5.2 on 2025-09-03 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_productimages_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.AddField(
            model_name='property',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.cpu'),
        ),
        migrations.AddField(
            model_name='property',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.memory'),
        ),
        migrations.AddField(
            model_name='property',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.rom'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rom',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
