# Generated by Django 5.2 on 2025-09-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_product_cpu_remove_product_memory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='product',
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ManyToManyField(related_name='images', to='home.product'),
        ),
    ]
