# Generated by Django 5.2 on 2025-09-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_productimages_product_productimages_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='property',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ram',
        ),
        migrations.AddField(
            model_name='product',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.cpu'),
        ),
        migrations.AddField(
            model_name='product',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.memory'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='home.rom'),
        ),
    ]
