# Generated by Django 5.2 on 2025-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_property_cpu_remove_property_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rom',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
